import type { OperationalData, ScenarioKey } from "./types";

const scenarios: Record<ScenarioKey, OperationalData> = {
  normal: {
    scenario: "normal",
    scenarioLabel: "Normal Operations",
    scenarioDescription: "Business-as-usual baseline. KPIs within target bands. ITIL controls green.",
    kpis: [
      {
        id: "revenue",
        label: "Monthly Revenue",
        value: "$1.82M",
        rawValue: 1_820_000,
        deltaPct: 4.2,
        trend: "up",
        target: "$1.75M",
        sparkline: [1.55, 1.61, 1.58, 1.66, 1.71, 1.74, 1.82],
        status: "healthy",
        context: "Consulting + hospitality + import lines combined",
      },
      {
        id: "conversion",
        label: "Conversion Rate",
        value: "3.8%",
        rawValue: 3.8,
        deltaPct: 0.6,
        trend: "up",
        target: "3.5%",
        sparkline: [3.4, 3.5, 3.6, 3.5, 3.7, 3.8, 3.8],
        status: "healthy",
        context: "Marketing-qualified lead → signed contract",
      },
      {
        id: "sla",
        label: "Service Desk SLA",
        value: "97.2%",
        rawValue: 97.2,
        deltaPct: 1.1,
        trend: "up",
        target: "> 95%",
        sparkline: [94, 94.5, 95.6, 96.1, 96.8, 97.0, 97.2],
        status: "healthy",
        context: "Incidents closed within SLA (ITIL Incident Mgmt)",
      },
      {
        id: "mttr",
        label: "Mean Time to Resolve",
        value: "2h 18m",
        rawValue: 138,
        deltaPct: -8.2,
        trend: "down",
        target: "< 3h",
        sparkline: [170, 165, 158, 150, 148, 142, 138],
        status: "healthy",
        context: "P1/P2 incidents — trailing 7-day avg",
      },
      {
        id: "incidents",
        label: "Active Incidents",
        value: "3",
        rawValue: 3,
        deltaPct: -40,
        trend: "down",
        target: "< 5",
        sparkline: [6, 7, 5, 4, 4, 3, 3],
        status: "healthy",
        context: "Open P1/P2 across BUs",
      },
      {
        id: "retention",
        label: "Customer Retention",
        value: "94.1%",
        rawValue: 94.1,
        deltaPct: 0.3,
        trend: "flat",
        target: "> 92%",
        sparkline: [93.5, 93.7, 93.8, 93.9, 94.0, 94.0, 94.1],
        status: "healthy",
        context: "Rolling 90-day net retention",
      },
    ],
    funnel: [
      { label: "Impressions", count: 482_000, note: "Paid + organic reach across all channels" },
      { label: "Marketing Qualified Leads", count: 4820, note: "1% conversion on impressions" },
      { label: "Sales Qualified Leads", count: 2106, note: "BANT-qualified by SDR team" },
      { label: "Proposals Sent", count: 744, note: "After discovery & scoping calls" },
      { label: "Closed-Won", count: 183, note: "New logo clients this month" },
    ],
    campaigns: [
      { channel: "LinkedIn Ads", spend: 12_400, leads: 412, deals: 24, cac: 517, status: "healthy" },
      { channel: "Google Search", spend: 18_900, leads: 886, deals: 47, cac: 402, status: "healthy" },
      { channel: "Content / SEO", spend: 4_200, leads: 298, deals: 19, cac: 221, status: "healthy" },
      { channel: "Partner referrals", spend: 2_100, leads: 94, deals: 28, cac: 75, status: "healthy" },
    ],
    projects: [
      { code: "PRJ-0421", name: "Salesforce → HubSpot migration", pm: "María López", status: "on-track", progressPct: 68, budgetUsedPct: 62, nextMilestone: "Data cutover · Apr 22" },
      { code: "PRJ-0388", name: "Customer Portal v2 (MVP)", pm: "Diego Ramírez", status: "mvp", progressPct: 85, budgetUsedPct: 78, nextMilestone: "Beta release · Apr 28" },
      { code: "PRJ-0502", name: "SOC2 Type II audit prep", pm: "Jessica Tran", status: "on-track", progressPct: 54, budgetUsedPct: 48, nextMilestone: "Evidence collection" },
      { code: "PRJ-0514", name: "AI-assisted support triage", pm: "Carlos Ng", status: "on-track", progressPct: 32, budgetUsedPct: 28, nextMilestone: "Model eval · May 06" },
      { code: "PRJ-0299", name: "AWS multi-region failover", pm: "Ana Pereira", status: "launched", progressPct: 100, budgetUsedPct: 96, nextMilestone: "Handover to SRE" },
    ],
    churn: { accountsAtRisk: 6, inactiveOver30Days: 4, estimatedMrrAtRisk: 18_400 },
    itOps: {
      openTickets: 142,
      p1: 0,
      p2: 2,
      changesThisWeek: 14,
      failedChanges: 0,
      mttrMinutes: 138,
      slaCompliancePct: 97.2,
      ticketDeltaPct: -6.3,
    },
    monthOverMonth: { revenueDeltaPct: 4.2, conversionDeltaPct: 0.6 },
  },

  crisis: {
    scenario: "crisis",
    scenarioLabel: "Crisis Mode",
    scenarioDescription:
      "Something broke. Conversion collapsed, SLAs are blown, incident backlog spiked. The rules engine lights up.",
    kpis: [
      {
        id: "revenue",
        label: "Monthly Revenue",
        value: "$1.42M",
        rawValue: 1_420_000,
        deltaPct: -18.4,
        trend: "down",
        target: "$1.75M",
        sparkline: [1.78, 1.74, 1.71, 1.62, 1.55, 1.48, 1.42],
        status: "breach",
        context: "Pipeline stalled after gateway outage",
      },
      {
        id: "conversion",
        label: "Conversion Rate",
        value: "2.4%",
        rawValue: 2.4,
        deltaPct: -31.4,
        trend: "down",
        target: "3.5%",
        sparkline: [3.6, 3.5, 3.3, 3.0, 2.8, 2.5, 2.4],
        status: "breach",
        context: "Checkout step-3 abandonment up 23%",
      },
      {
        id: "sla",
        label: "Service Desk SLA",
        value: "81.4%",
        rawValue: 81.4,
        deltaPct: -16.2,
        trend: "down",
        target: "> 95%",
        sparkline: [96, 94, 91, 88, 85, 83, 81.4],
        status: "breach",
        context: "Tier-1 queue overloaded since outage",
      },
      {
        id: "mttr",
        label: "Mean Time to Resolve",
        value: "6h 40m",
        rawValue: 400,
        deltaPct: 112,
        trend: "up",
        target: "< 3h",
        sparkline: [140, 180, 220, 280, 320, 370, 400],
        status: "breach",
        context: "Correlated incidents driving duplicated work",
      },
      {
        id: "incidents",
        label: "Active Incidents",
        value: "11",
        rawValue: 11,
        deltaPct: 175,
        trend: "up",
        target: "< 5",
        sparkline: [3, 4, 5, 7, 8, 10, 11],
        status: "breach",
        context: "1 P1 + 3 downstream P2s open",
      },
      {
        id: "retention",
        label: "Customer Retention",
        value: "88.4%",
        rawValue: 88.4,
        deltaPct: -5.7,
        trend: "down",
        target: "> 92%",
        sparkline: [93.7, 93.2, 92.4, 91.1, 90.0, 89.1, 88.4],
        status: "watch",
        context: "Early churn signals from top-20 accounts",
      },
    ],
    funnel: [
      { label: "Impressions", count: 445_000, note: "Campaigns paused during outage" },
      { label: "Marketing Qualified Leads", count: 4105, note: "Form conversion dropped 20%" },
      { label: "Sales Qualified Leads", count: 1602, note: "SDR capacity pulled into war room" },
      { label: "Proposals Sent", count: 388, note: "Delayed by trust issues post-outage" },
      { label: "Closed-Won", count: 94, note: "~49% of baseline" },
    ],
    campaigns: [
      { channel: "LinkedIn Ads", spend: 12_400, leads: 355, deals: 11, cac: 1_127, status: "breach" },
      { channel: "Google Search", spend: 18_900, leads: 720, deals: 22, cac: 859, status: "watch" },
      { channel: "Content / SEO", spend: 4_200, leads: 240, deals: 10, cac: 420, status: "watch" },
      { channel: "Partner referrals", spend: 2_100, leads: 61, deals: 14, cac: 150, status: "healthy" },
    ],
    projects: [
      { code: "PRJ-0421", name: "Salesforce → HubSpot migration", pm: "María López", status: "delayed", progressPct: 62, budgetUsedPct: 71, nextMilestone: "Cutover postponed · TBD" },
      { code: "PRJ-0388", name: "Customer Portal v2 (MVP)", pm: "Diego Ramírez", status: "at-risk", progressPct: 72, budgetUsedPct: 86, nextMilestone: "Scope trim review" },
      { code: "PRJ-0502", name: "SOC2 Type II audit prep", pm: "Jessica Tran", status: "at-risk", progressPct: 48, budgetUsedPct: 55, nextMilestone: "Incident docs backlog" },
      { code: "PRJ-0514", name: "AI-assisted support triage", pm: "Carlos Ng", status: "on-track", progressPct: 40, budgetUsedPct: 32, nextMilestone: "Fast-tracked for relief" },
      { code: "PRJ-0299", name: "AWS multi-region failover", pm: "Ana Pereira", status: "launched", progressPct: 100, budgetUsedPct: 96, nextMilestone: "Validated in outage" },
    ],
    churn: { accountsAtRisk: 18, inactiveOver30Days: 14, estimatedMrrAtRisk: 96_500 },
    itOps: {
      openTickets: 486,
      p1: 1,
      p2: 3,
      changesThisWeek: 22,
      failedChanges: 3,
      mttrMinutes: 400,
      slaCompliancePct: 81.4,
      ticketDeltaPct: 142,
    },
    monthOverMonth: { revenueDeltaPct: -18.4, conversionDeltaPct: -31.4 },
  },

  growth: {
    scenario: "growth",
    scenarioLabel: "Growth Phase",
    scenarioDescription:
      "Expansion is outpacing capacity. Metrics look great, ops is straining — the system should recommend scaling moves.",
    kpis: [
      {
        id: "revenue",
        label: "Monthly Revenue",
        value: "$2.51M",
        rawValue: 2_510_000,
        deltaPct: 37.9,
        trend: "up",
        target: "$1.75M",
        sparkline: [1.82, 1.95, 2.08, 2.21, 2.33, 2.44, 2.51],
        status: "healthy",
        context: "New enterprise cohort + hospitality peak",
      },
      {
        id: "conversion",
        label: "Conversion Rate",
        value: "5.1%",
        rawValue: 5.1,
        deltaPct: 34.2,
        trend: "up",
        target: "3.5%",
        sparkline: [3.8, 4.0, 4.3, 4.5, 4.7, 4.9, 5.1],
        status: "healthy",
        context: "Inbound demand outpacing sales capacity",
      },
      {
        id: "sla",
        label: "Service Desk SLA",
        value: "93.6%",
        rawValue: 93.6,
        deltaPct: -3.5,
        trend: "down",
        target: "> 95%",
        sparkline: [97, 96.5, 96, 95.2, 94.5, 94, 93.6],
        status: "watch",
        context: "Ticket volume +60%, headcount flat",
      },
      {
        id: "mttr",
        label: "Mean Time to Resolve",
        value: "2h 55m",
        rawValue: 175,
        deltaPct: 27,
        trend: "up",
        target: "< 3h",
        sparkline: [138, 145, 152, 160, 165, 170, 175],
        status: "watch",
        context: "Scaling pains — deploy frequency 3x",
      },
      {
        id: "incidents",
        label: "Active Incidents",
        value: "5",
        rawValue: 5,
        deltaPct: 66.6,
        trend: "up",
        target: "< 5",
        sparkline: [3, 3, 4, 4, 5, 5, 5],
        status: "watch",
        context: "Change volume driving noise",
      },
      {
        id: "retention",
        label: "Customer Retention",
        value: "96.2%",
        rawValue: 96.2,
        deltaPct: 2.2,
        trend: "up",
        target: "> 92%",
        sparkline: [94.1, 94.6, 95.0, 95.4, 95.8, 96.0, 96.2],
        status: "healthy",
        context: "Product-market fit solidifying",
      },
    ],
    funnel: [
      { label: "Impressions", count: 742_000, note: "Campaign budget increased 40%" },
      { label: "Marketing Qualified Leads", count: 7420, note: "Inbound demand surging" },
      { label: "Sales Qualified Leads", count: 3580, note: "SDR team at capacity" },
      { label: "Proposals Sent", count: 1491, note: "Response times slipping" },
      { label: "Closed-Won", count: 378, note: "2x baseline — hiring pipeline needed" },
    ],
    campaigns: [
      { channel: "LinkedIn Ads", spend: 21_000, leads: 812, deals: 62, cac: 339, status: "healthy" },
      { channel: "Google Search", spend: 28_500, leads: 1_640, deals: 118, cac: 241, status: "healthy" },
      { channel: "Content / SEO", spend: 6_800, leads: 744, deals: 58, cac: 117, status: "healthy" },
      { channel: "Partner referrals", spend: 3_400, leads: 228, deals: 66, cac: 52, status: "healthy" },
    ],
    projects: [
      { code: "PRJ-0421", name: "Salesforce → HubSpot migration", pm: "María López", status: "on-track", progressPct: 74, budgetUsedPct: 66, nextMilestone: "Data cutover · Apr 22" },
      { code: "PRJ-0388", name: "Customer Portal v2 (MVP)", pm: "Diego Ramírez", status: "launched", progressPct: 100, budgetUsedPct: 91, nextMilestone: "GA rollout — scale reads" },
      { code: "PRJ-0502", name: "SOC2 Type II audit prep", pm: "Jessica Tran", status: "on-track", progressPct: 62, budgetUsedPct: 52, nextMilestone: "Auditor kickoff" },
      { code: "PRJ-0514", name: "AI-assisted support triage", pm: "Carlos Ng", status: "mvp", progressPct: 55, budgetUsedPct: 41, nextMilestone: "Pilot w/ Tier-1 agents" },
      { code: "PRJ-0601", name: "Helpdesk capacity program", pm: "Sergio Luna", status: "at-risk", progressPct: 18, budgetUsedPct: 12, nextMilestone: "Hiring approval pending" },
    ],
    churn: { accountsAtRisk: 3, inactiveOver30Days: 2, estimatedMrrAtRisk: 8_200 },
    itOps: {
      openTickets: 318,
      p1: 0,
      p2: 4,
      changesThisWeek: 41,
      failedChanges: 2,
      mttrMinutes: 175,
      slaCompliancePct: 93.6,
      ticketDeltaPct: 58,
    },
    monthOverMonth: { revenueDeltaPct: 37.9, conversionDeltaPct: 34.2 },
  },
};

export function getScenario(key: ScenarioKey): OperationalData {
  return scenarios[key];
}

export const scenarioKeys: ScenarioKey[] = ["normal", "crisis", "growth"];
