import type { OperationalData, ScenarioKey } from "./types";

const scenarios: Record<ScenarioKey, OperationalData> = {
  normal: {
    scenario: "normal",
    scenarioLabel: "Normal Operations",
    scenarioDescription: "Business-as-usual baseline. KPIs within target bands.",
    kpis: [
      {
        id: "revenue",
        label: "Monthly Revenue",
        value: "$1.82M",
        rawValue: 1_820_000,
        deltaPct: 4.2,
        trend: "up",
        target: "$1.75M",
        sparkline: [1.55, 1.61, 1.58, 1.66, 1.71, 1.74, 1.82],
        status: "healthy",
        context: "Consulting + hospitality + import lines combined",
      },
      {
        id: "conversion",
        label: "Conversion Rate",
        value: "3.8%",
        rawValue: 3.8,
        deltaPct: 0.6,
        trend: "up",
        target: "3.5%",
        sparkline: [3.4, 3.5, 3.6, 3.5, 3.7, 3.8, 3.8],
        status: "healthy",
        context: "Lead → signed contract, 14-day trailing avg",
      },
      {
        id: "sla",
        label: "Support SLA",
        value: "1h 48m",
        rawValue: 108,
        deltaPct: -6.1,
        trend: "down",
        target: "< 2h",
        sparkline: [130, 125, 118, 115, 112, 110, 108],
        status: "healthy",
        context: "Tier 1 first-response, minutes",
      },
      {
        id: "productivity",
        label: "Team Productivity",
        value: "87",
        rawValue: 87,
        deltaPct: 1.4,
        trend: "up",
        target: "> 80",
        sparkline: [82, 83, 85, 84, 86, 86, 87],
        status: "healthy",
        context: "Composite index across 4 delivery teams",
      },
      {
        id: "incidents",
        label: "Active Incidents",
        value: "3",
        rawValue: 3,
        deltaPct: -40,
        trend: "down",
        target: "< 5",
        sparkline: [6, 7, 5, 4, 4, 3, 3],
        status: "healthy",
        context: "P1/P2 open, cross-BU",
      },
      {
        id: "retention",
        label: "Customer Retention",
        value: "94.1%",
        rawValue: 94.1,
        deltaPct: 0.3,
        trend: "flat",
        target: "> 92%",
        sparkline: [93.5, 93.7, 93.8, 93.9, 94.0, 94.0, 94.1],
        status: "healthy",
        context: "Rolling 90-day net retention",
      },
    ],
    funnel: [
      { label: "Leads", count: 4820 },
      { label: "Qualified", count: 2106 },
      { label: "Proposal", count: 744 },
      { label: "Closed Won", count: 183 },
    ],
    teams: [
      { team: "Consulting Delivery", productivity: 89, headcount: 14, sla: 105, slaTarget: 120 },
      { team: "Hospitality Ops", productivity: 85, headcount: 22, sla: 95, slaTarget: 120 },
      { team: "Imports / Logistics", productivity: 82, headcount: 9, sla: 140, slaTarget: 180 },
      { team: "Marketing & Growth", productivity: 91, headcount: 6, sla: 60, slaTarget: 90 },
    ],
    churn: { accountsAtRisk: 6, inactiveOver30Days: 4, estimatedMrrAtRisk: 18_400 },
    monthOverMonth: { revenueDeltaPct: 4.2, conversionDeltaPct: 0.6 },
  },

  crisis: {
    scenario: "crisis",
    scenarioLabel: "Crisis Mode",
    scenarioDescription:
      "Something broke. Conversion collapsed, SLAs are blown, churn risk spiked. Rules engine should light up.",
    kpis: [
      {
        id: "revenue",
        label: "Monthly Revenue",
        value: "$1.42M",
        rawValue: 1_420_000,
        deltaPct: -18.4,
        trend: "down",
        target: "$1.75M",
        sparkline: [1.78, 1.74, 1.71, 1.62, 1.55, 1.48, 1.42],
        status: "breach",
        context: "Consulting pipeline stalled, hospitality seasonally flat",
      },
      {
        id: "conversion",
        label: "Conversion Rate",
        value: "2.4%",
        rawValue: 2.4,
        deltaPct: -31.4,
        trend: "down",
        target: "3.5%",
        sparkline: [3.6, 3.5, 3.3, 3.0, 2.8, 2.5, 2.4],
        status: "breach",
        context: "Checkout step 3 abandonment up 23%",
      },
      {
        id: "sla",
        label: "Support SLA",
        value: "4h 12m",
        rawValue: 252,
        deltaPct: 92,
        trend: "up",
        target: "< 2h",
        sparkline: [115, 140, 165, 190, 215, 240, 252],
        status: "breach",
        context: "Tier 1 queue overloaded since outage",
      },
      {
        id: "productivity",
        label: "Team Productivity",
        value: "71",
        rawValue: 71,
        deltaPct: -14.4,
        trend: "down",
        target: "> 80",
        sparkline: [85, 84, 82, 79, 76, 73, 71],
        status: "breach",
        context: "War-room drain, context-switching",
      },
      {
        id: "incidents",
        label: "Active Incidents",
        value: "11",
        rawValue: 11,
        deltaPct: 175,
        trend: "up",
        target: "< 5",
        sparkline: [3, 4, 5, 7, 8, 10, 11],
        status: "breach",
        context: "Payment gateway P1 + 3 downstream",
      },
      {
        id: "retention",
        label: "Customer Retention",
        value: "88.4%",
        rawValue: 88.4,
        deltaPct: -5.7,
        trend: "down",
        target: "> 92%",
        sparkline: [93.7, 93.2, 92.4, 91.1, 90.0, 89.1, 88.4],
        status: "watch",
        context: "Early churn signals from top-20 accounts",
      },
    ],
    funnel: [
      { label: "Leads", count: 4105 },
      { label: "Qualified", count: 1602 },
      { label: "Proposal", count: 388 },
      { label: "Closed Won", count: 94 },
    ],
    teams: [
      { team: "Consulting Delivery", productivity: 72, headcount: 14, sla: 190, slaTarget: 120 },
      { team: "Hospitality Ops", productivity: 75, headcount: 22, sla: 150, slaTarget: 120 },
      { team: "Imports / Logistics", productivity: 68, headcount: 9, sla: 240, slaTarget: 180 },
      { team: "Marketing & Growth", productivity: 74, headcount: 6, sla: 95, slaTarget: 90 },
    ],
    churn: { accountsAtRisk: 18, inactiveOver30Days: 14, estimatedMrrAtRisk: 96_500 },
    monthOverMonth: { revenueDeltaPct: -18.4, conversionDeltaPct: -31.4 },
  },

  growth: {
    scenario: "growth",
    scenarioLabel: "Growth Phase",
    scenarioDescription:
      "Expansion is outpacing capacity. Metrics look great, but ops is straining — the system should recommend scaling moves.",
    kpis: [
      {
        id: "revenue",
        label: "Monthly Revenue",
        value: "$2.51M",
        rawValue: 2_510_000,
        deltaPct: 37.9,
        trend: "up",
        target: "$1.75M",
        sparkline: [1.82, 1.95, 2.08, 2.21, 2.33, 2.44, 2.51],
        status: "healthy",
        context: "New enterprise cohort + hospitality peak season",
      },
      {
        id: "conversion",
        label: "Conversion Rate",
        value: "5.1%",
        rawValue: 5.1,
        deltaPct: 34.2,
        trend: "up",
        target: "3.5%",
        sparkline: [3.8, 4.0, 4.3, 4.5, 4.7, 4.9, 5.1],
        status: "healthy",
        context: "Inbound demand outpacing sales capacity",
      },
      {
        id: "sla",
        label: "Support SLA",
        value: "2h 35m",
        rawValue: 155,
        deltaPct: 43.5,
        trend: "up",
        target: "< 2h",
        sparkline: [108, 115, 125, 135, 145, 150, 155],
        status: "watch",
        context: "Ticket volume up 60%, headcount flat",
      },
      {
        id: "productivity",
        label: "Team Productivity",
        value: "92",
        rawValue: 92,
        deltaPct: 5.7,
        trend: "up",
        target: "> 80",
        sparkline: [87, 88, 89, 90, 91, 91, 92],
        status: "healthy",
        context: "High utilization — burnout risk forming",
      },
      {
        id: "incidents",
        label: "Active Incidents",
        value: "5",
        rawValue: 5,
        deltaPct: 66.6,
        trend: "up",
        target: "< 5",
        sparkline: [3, 3, 4, 4, 5, 5, 5],
        status: "watch",
        context: "Scaling pains: deploy frequency up 3x",
      },
      {
        id: "retention",
        label: "Customer Retention",
        value: "96.2%",
        rawValue: 96.2,
        deltaPct: 2.2,
        trend: "up",
        target: "> 92%",
        sparkline: [94.1, 94.6, 95.0, 95.4, 95.8, 96.0, 96.2],
        status: "healthy",
        context: "Product-market fit solidifying",
      },
    ],
    funnel: [
      { label: "Leads", count: 7420 },
      { label: "Qualified", count: 3580 },
      { label: "Proposal", count: 1491 },
      { label: "Closed Won", count: 378 },
    ],
    teams: [
      { team: "Consulting Delivery", productivity: 94, headcount: 14, sla: 130, slaTarget: 120 },
      { team: "Hospitality Ops", productivity: 90, headcount: 22, sla: 135, slaTarget: 120 },
      { team: "Imports / Logistics", productivity: 88, headcount: 9, sla: 170, slaTarget: 180 },
      { team: "Marketing & Growth", productivity: 95, headcount: 6, sla: 80, slaTarget: 90 },
    ],
    churn: { accountsAtRisk: 3, inactiveOver30Days: 2, estimatedMrrAtRisk: 8_200 },
    monthOverMonth: { revenueDeltaPct: 37.9, conversionDeltaPct: 34.2 },
  },
};

export function getScenario(key: ScenarioKey): OperationalData {
  return scenarios[key];
}

export const scenarioKeys: ScenarioKey[] = ["normal", "crisis", "growth"];
