import Link from "next/link";
import { getScenario } from "@/lib/mock-data";
import type { ScenarioKey } from "@/lib/types";

function parseScenario(v: string | string[] | undefined): ScenarioKey {
  const s = Array.isArray(v) ? v[0] : v;
  if (s === "crisis" || s === "growth") return s;
  return "normal";
}

type Health = "healthy" | "watch" | "breach";

const healthBorder: Record<Health, string> = {
  healthy: "border-emerald-500/40",
  watch: "border-amber-500/40",
  breach: "border-rose-500/40",
};

const healthText: Record<Health, string> = {
  healthy: "text-emerald-300",
  watch: "text-amber-300",
  breach: "text-rose-300",
};

const healthDot: Record<Health, string> = {
  healthy: "bg-emerald-400",
  watch: "bg-amber-400",
  breach: "bg-rose-400",
};

export default async function WorkflowPage({
  searchParams,
}: {
  searchParams: Promise<{ scenario?: string }>;
}) {
  const params = await searchParams;
  const scenario = parseScenario(params.scenario);
  const data = getScenario(scenario);

  const nodes = [
    {
      label: "Lead",
      count: data.funnel[1].count.toLocaleString(),
      health: "healthy" as Health,
      measuring: "Marketing-qualified leads",
      description:
        "Top of funnel volume generated by campaigns, SEO and referrals. Measures how much demand is entering the system each month.",
    },
    {
      label: "Qualification",
      count: data.funnel[2].count.toLocaleString(),
      health: "healthy" as Health,
      measuring: "SDR-qualified opportunities",
      description:
        "Leads that pass BANT (budget, authority, need, timeline). Shows how well marketing demand matches an ideal customer profile.",
    },
    {
      label: "Proposal",
      count: data.funnel[3].count.toLocaleString(),
      health: scenario === "crisis" ? ("breach" as Health) : ("healthy" as Health),
      measuring: "Active proposals in flight",
      description:
        "Deals in commercial negotiation. Bottlenecks here usually mean pricing, legal or scope friction — not product fit.",
    },
    {
      label: "Closed-Won",
      count: data.funnel[4].count.toLocaleString(),
      health: "healthy" as Health,
      measuring: "New clients acquired this month",
      description:
        "The monthly list of new logos. This is the number that ultimately funds growth and compounds month over month.",
    },
    {
      label: "Onboarding",
      count: "—",
      health: scenario === "growth" ? ("watch" as Health) : ("healthy" as Health),
      measuring: "Time-to-value & CSM capacity",
      description:
        "How quickly a new client reaches first value. Under growth scenarios, CSM capacity is the first thing to strain.",
    },
    {
      label: "Retention",
      count: `${data.kpis.find((k) => k.id === "retention")?.value}`,
      health: scenario === "crisis" ? ("watch" as Health) : ("healthy" as Health),
      measuring: "Net revenue retention",
      description: `Rolling 90-day retention across the account base. ${data.churn.accountsAtRisk} accounts currently flagged as at-risk.`,
    },
  ];

  return (
    <div className="mx-auto w-full max-w-7xl px-6 py-8">
      <header className="mb-8">
        <div className="flex items-center justify-between gap-4">
          <div>
            <p className="text-xs font-medium uppercase tracking-[0.2em] text-emerald-300">Operational Workflow</p>
            <h1 className="mt-1 text-2xl font-semibold tracking-tight text-white sm:text-3xl">
              Lead → Retention Flow
            </h1>
            <p className="mt-2 max-w-3xl text-sm text-slate-400">
              End-to-end operational stages with current volume, health and what each step is measuring. Health is
              computed against targets by the same rules engine that powers the dashboard recommendations.
            </p>
          </div>
          <Link
            href="/"
            className="hidden rounded-full border border-white/10 px-4 py-2 text-xs text-slate-300 hover:bg-white/5 sm:inline-flex"
          >
            ← Dashboard
          </Link>
        </div>
      </header>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
        {nodes.map((n, i) => (
          <div
            key={n.label}
            className={`rounded-2xl border bg-[var(--surface-2)] p-5 ${healthBorder[n.health]}`}
          >
            <div className="mb-2 flex items-center gap-2">
              <span className={`h-2 w-2 rounded-full ${healthDot[n.health]}`} />
              <span className="text-[10px] font-medium uppercase tracking-wider text-slate-400">
                Stage {i + 1}
              </span>
            </div>
            <p className={`text-lg font-semibold ${healthText[n.health]}`}>{n.label}</p>
            <p className="mt-1 text-3xl font-bold text-white">{n.count}</p>
            <p className="mt-3 text-[11px] font-semibold uppercase tracking-wider text-emerald-300">
              What we measure
            </p>
            <p className="mt-1 text-xs text-slate-300">{n.measuring}</p>
            <p className="mt-2 text-xs leading-relaxed text-slate-400">{n.description}</p>
          </div>
        ))}
      </div>

      <section className="mt-10 grid grid-cols-1 gap-4 md:grid-cols-3">
        <InfoCard title="What this shows" body="How I think about operations — every business reduces to a funnel with measurable health gates, whether it is SaaS, consulting or hospitality." />
        <InfoCard title="Why it matters" body="Directors and VPs are paid to spot where the funnel leaks and align the right owner to act. Metrics alone are insufficient without accountability." />
        <InfoCard title="How it works" body="A pure-TypeScript rules engine scores each stage against targets and surfaces recommendations with estimated impact, effort and owner." />
      </section>
    </div>
  );
}

function InfoCard({ title, body }: { title: string; body: string }) {
  return (
    <div className="rounded-2xl border border-white/5 bg-[var(--surface)] p-5">
      <p className="text-xs font-semibold uppercase tracking-wider text-emerald-300">{title}</p>
      <p className="mt-2 text-sm text-slate-300">{body}</p>
    </div>
  );
}
